language: android

android:
  components:
    - build-tools-19.0.3
    - android-19

before_script:
  - android update project -p . -n DrawMeFairy -t android-19
  
script:
  - ant debug
  
before_deploy:
  - gem install multipart-post
  - find . -name "*.apk"
  
deploy:
  provider: testfairy
  app-file: draw-me-a-fairy.apk
  keystore-file: certs/debug.keystore
  storepass: android
  alias: androiddebugkey
  metrics: "cpu,memory,logcat"
  skip_cleanup: true
  on:
    all_branches: true
  api-key:
    "foo"
  
